language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t david8087/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true david8087/docker-react npm run test